### ISSUE TITLE
Issue with Skill Prediction

### ISSUE THREAD

**Issue by Leyki** [AlteriaX/LocationInfo#1]
Hello and sorry for creating this issue here however since issues are disabled in that repository i felt obligued to do this. As always, the common goal in purpose is to contribute to the code, i'm only meaning to do that.

So, without further do...

I have all of this issues: https://github.com/tera-mods/skill-prediction/issues ! Ples flex!

**Comment by AlteriaX** [comment]
Kys btw!!!
